//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketplace.context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sample_1Entities24 : DbContext
    {
        public Sample_1Entities24()
            : base("name=Sample_1Entities24")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Download> Downloads { get; set; }
        public virtual DbSet<SellerNote> SellerNotes { get; set; }
        public virtual DbSet<SellerNotesReportedIssue> SellerNotesReportedIssues { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
